import { useState } from "react";
import "../App.css";

const API_URL =
  import.meta.env.VITE_API_URL || "http://localhost:5000/api";

interface OTPMessage {
  phone: string;
  message: string;
  createdAt: string;
}

interface MockEmail {
  email: string;
  subject: string;
  message: string;
  createdAt: string;
}

function DeveloperTools() {
  const [secret, setSecret] = useState("");
  const [otps, setOtps] = useState<OTPMessage[]>([]);
  const [emails, setEmails] = useState<MockEmail[]>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState("");

  const fetchData = async (type: "otps" | "emails") => {
    if (!secret.trim()) {
      setError("Please enter the developer access key.");
      return;
    }

    setError("");
    setLoading(type);

    try {
      const response = await fetch(
        `${API_URL}/dev/${type}`,
        {
          headers: {
            "x-dev-endpoint-secret": secret,
          },
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.message || "Unable to fetch developer data."
        );
      }

      if (type === "otps") {
        setOtps(data.messages || []);
      } else {
        setEmails(data.emails || []);
      }
    } catch (err: any) {
      setError(
        err.message || "Unable to connect to the backend."
      );
    } finally {
      setLoading("");
    }
  };

  return (
    <div className="developer-page">
      <div className="developer-container">

        <div className="developer-header">
          <div className="brand-badge">
            Evaluation tools
          </div>

          <h1>Developer tools</h1>

          <p>
            Retrieve mock OTPs and password-reset emails
            generated by the application.
          </p>
        </div>

        <div className="developer-card">

          <div className="form-group">
            <label htmlFor="developer-secret">
              Developer access key
            </label>

            <input
              id="developer-secret"
              type="password"
              value={secret}
              onChange={(e) => setSecret(e.target.value)}
              placeholder="Enter developer access key"
            />
          </div>

          {error && (
            <div className="form-error">
              {error}
            </div>
          )}

          <div className="developer-actions">
            <button
              type="button"
              className="submit-btn"
              onClick={() => fetchData("otps")}
              disabled={loading !== ""}
            >
              {loading === "otps"
                ? "Loading..."
                : "View OTPs"}
            </button>

            <button
              type="button"
              className="enable-2fa-btn"
              onClick={() => fetchData("emails")}
              disabled={loading !== ""}
            >
              {loading === "emails"
                ? "Loading..."
                : "View reset emails"}
            </button>
          </div>

        </div>

        {otps.length > 0 && (
          <div className="developer-results">
            <h2>Mock OTPs</h2>

            {otps.map((otp, index) => (
              <div
                className="developer-result"
                key={index}
              >
                <strong>{otp.message}</strong>
                <span>{otp.phone}</span>
                <small>
                  {new Date(otp.createdAt).toLocaleString()}
                </small>
              </div>
            ))}
          </div>
        )}

        {emails.length > 0 && (
          <div className="developer-results">
            <h2>Password reset emails</h2>

            {emails.map((email, index) => (
              <div
                className="developer-result"
                key={index}
              >
                <strong>{email.subject}</strong>
                <span>To: {email.email}</span>
                <p>{email.message}</p>
                <small>
                  {new Date(email.createdAt).toLocaleString()}
                </small>
              </div>
            ))}
          </div>
        )}

      </div>
    </div>
  );
}

export default DeveloperTools;